# Generated by Django 6.0.6 on 2026-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(db_index=True, max_length=200)),
                ("date", models.DateField(db_index=True)),
                (
                    "rain",
                    models.FloatField(
                        blank=True, help_text="Precipitation (inches)", null=True
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True, help_text="Avg wind speed (mph)", null=True
                    ),
                ),
                (
                    "wind_dir",
                    models.FloatField(
                        blank=True, help_text="Wind direction (degrees)", null=True
                    ),
                ),
                (
                    "max_wind_speed",
                    models.FloatField(
                        blank=True, help_text="Fastest wind speed (mph)", null=True
                    ),
                ),
                (
                    "air_temp",
                    models.FloatField(help_text="Average of TMAX and TMIN (°F)"),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("day_of_year", models.IntegerField()),
                (
                    "prev_day_temp",
                    models.FloatField(
                        blank=True, help_text="Previous day air temp (°F)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["station", "date"],
                        name="weather_wea_station_28665d_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="weather_wea_year_77184d_idx"
                    ),
                ],
                "unique_together": {("station", "date")},
            },
        ),
    ]
